

def test_row_get_treats_only_missing_and_null_as_absent():
    """Three modules had their own copy; this is the one. 0 and "" are values."""
    import sqlite3
    from app.db import row_get
    conn = sqlite3.connect(":memory:"); conn.row_factory = sqlite3.Row
    row = conn.execute("SELECT 0 AS zero, '' AS empty, NULL AS absent, 7 AS seven").fetchone()
    assert row_get(row, "zero", 9) == 0
    assert row_get(row, "empty", "x") == ""
    assert row_get(row, "absent", "dflt") == "dflt"
    assert row_get(row, "seven") == 7
    assert row_get(row, "no_such_column", "dflt") == "dflt"
    assert row_get({"a": None}, "a", 1) == 1 and row_get({}, "a", 2) == 2


def test_every_export_starts_from_the_same_eight_lines():
    """Three export routes each carried the same preamble, ending in a one-line
    run description that had drifted once already."""
    import inspect
    from app.web import routes_runs
    src = inspect.getsource(routes_runs)
    assert src.count("= _export_parts(request, run_id, row)") == 3
    assert src.count("def _export_parts(") == 1
    assert src.count("generated by Deep Research") == 1
